"""Regenerate the synthetic three-regime validation figure from
`docs/hurst_dfa.py` WITHOUT modifying that file (it is the frozen reference
implementation: its purity is what makes re-validation meaningful).

Two things are handled here, in the export layer only:

1. The reference script hard-codes `plt.savefig("/home/claude/hurst_analysis.png")`,
   a path from the machine where it was written. We run it as `__main__` via
   runpy and redirect that one call to our output path.
2. Its figure text is in Spanish. For the portfolio it must read in English, so
   we relabel the finished `Figure` right before it is saved — no edit to the
   reference, and the plotted numbers are untouched.

On the regime labels: the generator in the reference is an AR(1) on returns with
`phi = 2*(H - 0.5)`, an approximation (its own docstring says so). Its "H" names
the generator, it is not a true fBm H, and the estimator does not recover those
magnitudes — the mean-reverting third comes back near 0.45, not 0.30. So the
labels carry the MEASURED rolling-H mean per regime, marked as an estimate, and
the caption claims only what the figure demonstrates: ordering and separation.

Usage:
    python scripts/export_synthetic_validation.py <out_png>
"""
from __future__ import annotations

import runpy
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np

REFERENCE = Path(__file__).resolve().parent.parent / "docs" / "hurst_dfa.py"

# Exact strings emitted by the reference script -> portfolio English.
# Anything the reference prints that is not in this map is reported at the end
# of the run, so a change upstream cannot leave Spanish text in silently.
TEXT_MAP = {
    "Régimen de mercado vía dimensión fractal (DFA)":
        "DFA estimator validation on synthetic regimes",
    "Precio  —  datos sinteticos (3 regimenes conocidos)":
        "Price — synthetic series built from three consecutive regimes",
    "precio": "price",
    "H (Hurst)": "H (Hurst, DFA)",
    "D = 2 − H\n(dim. fractal)": "D = 2 − H\n(fractal dimension)",
    "barra (tiempo)": "bar (time)",
    "↑ tendencia (continuación)": "↑ persistent (trend continuation)",
    "↓ reversión (mean-revert)": "↓ anti-persistent (mean reversion)",
    "más rugosa →": "rougher →",
}

REGIME_NAMES = ["TRENDING", "RANDOM WALK", "MEAN-REVERTING"]

CAPTION = ("Regimes are generated by an AR(1) on returns, so the generator's H is "
           "nominal, not a true fBm H: the figure demonstrates that the estimator "
           "orders and separates the three regimes, not that it recovers their "
           "magnitudes.")


def regime_estimates(ax_hurst, bounds: list[float], window: int = 120) -> list[float]:
    """Mean rolling H over the windows that fall ENTIRELY inside each regime.

    A window straddling a boundary mixes two regimes, so it is excluded — that
    is the only way the per-regime number means anything.
    """
    idx, h = (np.asarray(a, dtype=float) for a in ax_hurst.lines[0].get_data())
    edges = [0.0, *bounds, float(idx.max()) + 1]
    means = []
    for lo, hi in zip(edges[:-1], edges[1:]):
        sel = (idx >= lo + window) & (idx < hi)
        means.append(float(np.nanmean(h[sel])) if sel.any() else float("nan"))
    return means


def relabel(fig) -> list[str]:
    """Translate the figure in place. Returns any text left untranslated."""
    axes = fig.get_axes()
    ax_price, ax_hurst = axes[0], axes[1]

    # Regime boundaries = the dashed verticals the reference draws on the price panel.
    bounds = sorted(ln.get_xdata()[0] for ln in ax_price.lines
                    if ln.get_linestyle() in ("--", (0, (6.4, 1.6))) and len(set(ln.get_xdata())) == 1)
    estimates = regime_estimates(ax_hurst, list(bounds))

    regime_labels = {}
    for name, est in zip(REGIME_NAMES, estimates):
        regime_labels[name] = f"{name}\nest. H≈{est:.2f}"

    leftover: list[str] = []
    # Sweep every Text child of each axes rather than `ax.title` alone: a title
    # set with loc="left" is a different artist, and reading only the centered
    # one silently reports success while leaving Spanish on the figure.
    # Axis labels hang off the axis, not the axes, so they are added by hand.
    artists = list(fig.texts)
    for ax in axes:
        artists.extend(c for c in ax.get_children() if isinstance(c, mtext.Text))
        artists.append(ax.xaxis.label)
        artists.append(ax.yaxis.label)

    for art in artists:
        s = art.get_text()
        if not s.strip():
            continue
        if s in TEXT_MAP:
            art.set_text(TEXT_MAP[s])
            if s.startswith("↑"):
                # The upper LEFT of the H panel is exactly where the trending
                # regime peaks; the callout has to sit where the curve is not.
                art.set_position((ax_hurst.get_xlim()[1], art.get_position()[1]))
                art.set_ha("right")
            continue
        # Regime callouts arrive as "TENDENCIA\nH≈0.72" — keyed by their first word.
        head = s.split("\n")[0].strip().upper()
        matched = {"TENDENCIA": 0, "ALEATORIO": 1, "REVERSIÓN": 2, "REVERSION": 2}.get(head)
        if matched is not None:
            art.set_text(regime_labels[REGIME_NAMES[matched]])
            continue
        leftover.append(s)

    fig.text(0.125, 0.005, CAPTION, ha="left", va="bottom", fontsize=7.5,
             color="#7d8aa3", wrap=True)
    return leftover


def main() -> None:
    out = Path(sys.argv[1]).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    original_savefig = plt.savefig
    report: dict[str, list[str]] = {}

    def savefig(_path, *args, **kwargs):
        report["leftover"] = relabel(plt.gcf())
        return original_savefig(out, *args, **kwargs)

    plt.savefig = savefig
    try:
        runpy.run_path(str(REFERENCE), run_name="__main__")
    finally:
        plt.savefig = original_savefig

    leftover = report.get("leftover", [])
    if leftover:
        print("  WARNING: text left untranslated:")
        for s in leftover:
            print(f"    {s!r}")
    else:
        print("  all figure text translated")
    print(f"  wrote {out}")


if __name__ == "__main__":
    main()
